spring.application.name=user
logging.level.org.springframework=DEBUG
logging.level.com.managment.api=DEBUG

#definir puerto de ejecucion de la aplicacion.
server.port=8095
#URL del proyecto
server.servlet.context-path=/api
#cadena de conexion base de datos.
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=UsersApp;encrypt=false;
spring.datasource.username=userapp
spring.datasource.password=Admin123
#driver
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


